#作者：Tioks0
#链接：https://juejin.im/post/5ba22293e51d450e46282d68
#来源：掘金
#著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
# 解决xcode10对版本号警告的问题.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end

use_frameworks!

target 'PoporUI_Example' do
  pod 'PoporUI', :path => '../'
  pod 'Masonry'
  
  target 'PoporUI_Tests' do
      inherit! :search_paths
      
      
  end
end
