use_frameworks!

# 推荐继续使用 传统的 pod
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://cdn.cocoapods.org/'


# 推荐继续使用 传统的 pod
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://cdn.cocoapods.org/'

target 'PoporUI_Example' do
  #pod 'PoporFoundation', '1.15'
  
  pod 'PoporUI', :path => '../'
  pod 'Masonry'
  
  #pod 'PoporFoundation', :path => '/Users/popor/Documents/wkq/GitHubSDK/PoporFoundation', :tag=>'1.13'
  target 'PoporUI_Tests' do
      inherit! :search_paths
      
      
  end
end
